### ISSUE TITLE
Opening a new video

### ISSUE THREAD

**Issue by itsgeekhokage** [codebyaadi/vitube-streaming-platform#1]
a video works only when we click the caption/heading for it, it will be better if it will work for video img as well
@codebyaadi can you assign me this

**Comment by codebyaadi** [comment]
> a video works only when we click the caption/heading for it, it will be better if it will work for video img as well @codebyaadi can you assign me this

Thanks for taking this on, @Shivam36998! Looking forward to the improvement!
